Repository PCON-Hacktoberfest-2022/Textutils, pull requests merged in 2022-10, with the labels that each got.

#11 captalise first word feature
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#17 Add the code to toggle the message of dark and light mode
  package-lock.json
  src/components/Navbar.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#18 adding line break feature
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added Remove Punctuation Feature!
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#24 added the text to speech feature
  package-lock.json
  src/components/TextForm.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#30 remove line break feature
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added Paste from clipboard feature.
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#39 Fix: remove '?' when handling punctuation removal
  src/components/TextForm.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#42 Fix: general syntax errors
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#46 Resolved issue #22
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#47 download file feature
  src/components/TextForm.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#51 Added toggle case feature
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#53 Bug in Capitalize first word [fixes #45]
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#58 #2 Made the page little more attractive
  public/index.html
  src/App.css
  src/App.js
  src/components/TextForm.js
  src/index.css
Labels: hacktoberfest, hacktoberfest-accepted

#60 Added feature undo text
  src/components/TextForm.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#67 corrected spelling mistake
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted

#74 Collapse first content of About page
  src/App.css
  src/components/About.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#75 Updated speak feature by adding pause feature and added their respective icons
  package-lock.json
  package.json
  src/components/TextForm.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#78 Resolved Issue #77
  src/components/TextForm.js
Labels: bug, hacktoberfest, hacktoberfest-accepted

#79 issue#49-spell check feature added
  src/components/TextForm.js
Labels: hacktoberfest, hacktoberfest-accepted
